# Site settings
title: The Computational Protein Description project
description: > The CPD project is trying to aggressively refactor
	computerized protein classification, identification, and curation.
baseurl: ""
url: "https://proteins.github.io" # the base hostname & protocol for your site
github_username:  proteins

# Build settings
markdown: kramdown
